name: Trigger Vercel Deploy on New Pixelfed Post

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restore cached last Pixelfed post ID
        uses: actions/cache@v4
        with:
          path: .last_pixelfed_id
          key: pixelfed-id-cache

      - name: Check Pixelfed Atom feed and trigger deploy if new post
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: |
          FEED_URL="https://pixelfed.social/users/ruwaiz.atom"
          ID_FILE=".last_pixelfed_id"

          # Get the first <id> tag from the Atom feed (latest post)
          LATEST_ID=$(curl -s "$FEED_URL" | grep -m 1 "<id>" | sed -E 's|.*<id>(.*)</id>.*|\1|')

          echo "Latest Pixelfed post ID: $LATEST_ID"

          if [ -f "$ID_FILE" ];_]()
